### ISSUE TITLE
DOS09 in EPROM

### ISSUE THREAD

**Issue by dFlandre** [nbrok/DOS09#1]
Hi Nick,
I discovered your DOS09 project. I plan to try it on the SBC I designed and manufactured. For that, I have to make an expansion card for CF card, it is in progress...
I have a comment about your code: I thought about implementing DOS09 in EPROM. For this, I think it would be a good idea to gather all the variables and buffers in a single area that could be easily placed in RAM.
Thanks for your work.
David.

**Comment by nbrok** [comment]
As stated it is still in development and although it can be used it is not suitable for production use. The dos is written for RAM use because I use many buffers in RAM and many things aren't complete or don't work properly yet. It works fine for me. Your remark to gather all RAM used area's in one continuous area isn't a bad idea at all. I'll work on gathering all used RAM locations into one area. Programming the OS into EPROM has it's own issues because the CF routines aren't thoroughly tested yet and lacks on error detection. The publication is done to give other people some hints using a simple os as this one. (I use only one slice of 1.3 MB of CF because not enough memory.)  I was happier with FATFS routines written in 6809 assembly code, because I have no good C compiler for the 6809 and my system. Some comments in the source-code are still in Dutch but some are also in English. But any comment is appreciated.

**Comment by nbrok** [comment]
RAM variables moved to separate file dosvar.asm
